repos:
  # - repo: https://github.com/gherynos/pre-commit-java
  #   rev: v0.2.1  # Use the ref you want to point at
  #   hooks:
  #     - id: pmd
  #       exclude: /test/
  #     - id: cpd
  #       exclude: /test/
  #     - id: checkstyle
  #       exclude: /test/

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.2
      hooks:
        - id: gitleaks
    # ...